// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/mooha76/Kofee/Proxy_Service/api"
	"github.com/mooha76/Kofee/Proxy_Service/api/handler"
	"github.com/mooha76/Kofee/Proxy_Service/client"
	"github.com/mooha76/Kofee/Proxy_Service/config"
)

// Injectors from wire.go:

func InitializeApi(cfg *config.Config) (*api.Server, error) {
	authClient, err := client.NewAuthClient(cfg)
	if err != nil {
		return nil, err
	}
	authHandler := handler.NewAuthHandler(authClient)
	merchantClient, err := client.NewMerchantClient(cfg)
	if err != nil {
		return nil, err
	}
	merchantHandler := handler.NewMerchantHandler(merchantClient)
	userClient, err := client.NewUserClient(cfg)
	if err != nil {
		return nil, err
	}
	userHandler := handler.NewUserHandler(userClient)
	partnerClient, err := client.NewPartnerClient(cfg)
	if err != nil {
		return nil, err
	}
	partnerHandler := handler.NewPartnerHandler(partnerClient)
	server := api.NewServerHTTP(cfg, authHandler, merchantHandler, userHandler, partnerHandler)
	return server, nil
}
