// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/mooha76/Kofee/User_Service/api"
	"github.com/mooha76/Kofee/User_Service/api/service"
	"github.com/mooha76/Kofee/User_Service/config"
	"github.com/mooha76/Kofee/User_Service/db"
	"github.com/mooha76/Kofee/User_Service/repository"
	"github.com/mooha76/Kofee/User_Service/usecase"
)

// Injectors from wire.go:

func InitializeService(cfg *config.Config) (*api.ServiceServer, error) {
	sqlxDB, err := db.InitializeSQLXDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(sqlxDB)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userServiceServer := service.NewUserServiceServer(userUsecase)
	serviceServer, err := api.NewServerGRPC(cfg, userServiceServer)
	if err != nil {
		return nil, err
	}
	return serviceServer, nil
}
