// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/mooha76/GoUser_Service-Grpc/api"
	"github.com/mooha76/GoUser_Service-Grpc/api/service"
	"github.com/mooha76/GoUser_Service-Grpc/config"
	"github.com/mooha76/GoUser_Service-Grpc/db"
	"github.com/mooha76/GoUser_Service-Grpc/repository"
	"github.com/mooha76/GoUser_Service-Grpc/usecase"
)

// Injectors from wire.go:

func InitializeService(cfg *config.Config) (*api.ServiceServer, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userServiceServer := service.NewUserServiceServer(userUsecase)
	serviceServer, err := api.NewServerGRPC(cfg, userServiceServer)
	if err != nil {
		return nil, err
	}
	return serviceServer, nil
}
