INSERT INTO "IDENTITYTYPES"(
	"IDENTITYTYPEID", "IDENTITYTYPENAME")
	VALUES (2, 'Partner');


INSERT INTO "SERVICES"(
	"SERVICEID", "SERVICENAME", "SERVICECODE", "IDENTITYTYPEID")
	VALUES (11, 'Create New Partner', 550, 2);

INSERT INTO "ACCOUNTTYPES"(
	"ACCOUNTTYPEID", "ACCOUNTTYPENAME")
	VALUES (2, 'Partner Account');

INSERT INTO "COMMISSIONPLANS"(
	"COMMISSIONPLANID", "COMMISSIONPLANNAME")
	VALUES (5, 'Default Partner commission plan');

INSERT INTO "SERVICES"(
	"SERVICEID", "SERVICENAME", "SERVICECODE", "IDENTITYTYPEID")
	VALUES (15, 'Credit To Partner Account', 551, 2);

INSERT INTO "COMMISSIONTYPES"(
	"COMMISSIONTYPEID", "COMMISSIONTYPENAME")
	VALUES (1, 'Percentage');

INSERT INTO public."COMMISSIONRATES"(
	"COMMISSIONRATEID", "COMMISSIONPLANID", "MINTRANSACTIONAMOUNT", "MAXTRANSACTIONAMOUNT", "COMMISSIONRATE", "COMMISSIONTYPEID", "ISACTIVE", "SERVICEID")
	VALUES (9, 5, 0.0000001, 10000000, 10, 1, true, 15);

INSERT INTO "CURRENCIES"(
	"CURRENCYID", "SHORTNAME", "CURRENCYCODE", "FULLNAME", "SYMBOL")
	VALUES (99, 'USD', 0076, 'US Dollar', '$');


INSERT INTO "WITHDRAWALREQUESTSTATUSES"(
	"WITHDRAWLREQUESTSTAUSID", "STATUS")
	VALUES (1, 'REQUESTED');

INSERT INTO "WITHDRAWALREQUESTSTATUSES"(
	"WITHDRAWLREQUESTSTAUSID", "STATUS")
	VALUES (2, 'APPROVED');

INSERT INTO "WITHDRAWALREQUESTSTATUSES"(
	"WITHDRAWLREQUESTSTAUSID", "STATUS")
	VALUES (3, 'REJECTED');

INSERT INTO "WITHDRAWALREQUESTTYPES"(
	"WITHDRAWALREQUESTTYPEID", "NAME")
	VALUES (5, 'WALLET');

INSERT INTO "WITHDRAWALREQUESTTYPES"(
	"WITHDRAWALREQUESTTYPEID", "NAME")
	VALUES (6, 'BANK');

INSERT INTO "WITHDRAWALREQUESTTYPES"(
	"WITHDRAWALREQUESTTYPEID", "NAME")
	VALUES (7, 'TAAJ');


INSERT INTO "TRANSFERTYPES"(
	"TRANSFERTYPEID", "NAME")
	VALUES (105, 'CREDIT TO PARTNER ACCOUNT');

INSERT INTO "TRANSFERSTATUSES"(
	"STATUSID", "NAME")
	VALUES (3, 'Completed');

INSERT INTO "TRANSFERSTATUSES"(
	"STATUSID", "NAME")
	VALUES (5, 'Failed');

INSERT INTO "TRANSFERSTATUSES"(
	"STATUSID", "NAME")
	VALUES (7, 'Rejected');

INSERT INTO "TRANSFERSTATUSES"(
	"STATUSID", "NAME")
	VALUES (2, 'InProgress');

INSERT INTO "TRANSFERSTATUSES"(
	"STATUSID", "NAME")
	VALUES (4, 'Ambiguous');