CREATE TABLE "ACCOUNT" (
  "ACCOUNTID" BIGSERIAL PRIMARY KEY,
  "ACCOUNTNO" BIGINT UNIQUE NOT NULL,
  "ACCOUNTTYPEID" integer NOT NULL,
  "WITHDRAWALREQUEST" BIGINT DEFAULT 0,
  "CREDIT" BIGINT NOT NULL,
  "DEBIT" BIGINT NOT NULL,
  "COMMISION" BIGINT NOT NULL,
  "COMMISIONPLANID" BIGINT NOT NULL,
  "CURRENCYID" BIGINT NOT NULL,
  "CREATEDDATE" timestamp NOT NULL DEFAULT (now()),
  "UPDATEDDATE" timestamp
);

CREATE TABLE "TRANSFERS" (
  "TRANSFERID" BIGSERIAL PRIMARY KEY,
  "TRANSFERTYPEID" BIGINT NOT NULL,
  "TRANSFERAMOUNT" BIGINT NOT NULL,
  "CHARGEAMOUNT" BIGINT NOT NULL,
  "STATUSID" BIGINT NOT NULL,
  "SERVICEID" BIGINT NOT NULL,
  "SENDERTRANSFERID" BIGINT NOT NULL,
  "CREATEDDATE" timestamptz NOT NULL DEFAULT (now()),
  "UPDATEDDATE" timestamptz,
  "SENDERMOBILE" BIGINT NOT NULL,
  "RECEIVERACCOUNTID" BIGINT NOT NULL,
  "TRANSFERDESCRIPTION" varchar,
  "CHARGEDACCOUNTID" BIGINT NOT NULL,
  "CURRENCYID" BIGINT NOT NULL,
  "RECEIVERIDENTITYTYPEID" BIGINT NOT NULL
);

CREATE TABLE "TRANSFERTYPES" (
  "TRANSFERTYPEID" BIGSERIAL PRIMARY KEY,
  "NAME" varchar,
  "ISACTIVE" bool DEFAULT true,
  "CREATEDDATE" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "TRANSFERSTATUSES" (
  "STATUSID" BIGSERIAL PRIMARY KEY,
  "NAME" varchar,
  "ISACTIVE" bool DEFAULT true,
  "CREATEDDATE" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "ACCOUNTTYPES" (
  "ACCOUNTTYPEID" integer PRIMARY KEY,
  "ACCOUNTTYPENAME" varchar NOT NULL,
  "ISACTIVE" bool DEFAULT true,
  "CREATEDDATE" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "PARTNERS" (
  "PARTNERID" BIGSERIAL PRIMARY KEY,
  "FIRSTNAME" varchar NOT NULL,
  "MIDDLENAME" varchar NOT NULL,
  "LASTNAME" varchar NOT NULL,
  "USERNAME" varchar NOT NULL,
  "PASSWORD" varchar NOT NULL,
  "WITHDRAWALREQUESTTYPEID" integer NOT NULL,
  "IDENTITYTYPEID" integer NOT NULL,
  "MOBILE" integer NOT NULL,
  "ACCOUNTNO" integer UNIQUE NOT NULL,
  "COMMISSIONPLANID" integer NOT NULL,
  "AGE" integer NOT NULL,
  "GENDER" varchar NOT NULL,
  "EMAIL" varchar NOT NULL,
  "ISACTIVE" bool DEFAULT false,
  "ISMOBILEACTIVE" bool DEFAULT false,
  "ISBLOCKED" bool DEFAULT false,
  "ISBLACKLIST" bool DEFAULT false,
  "CREATEDDATE" timestamptz NOT NULL DEFAULT (now()),
  "UPDATEDDATE" timestamptz
);

CREATE TABLE "PARTNERACCOUNTS" (
  "PARTNERACCOUNTID" BIGSERIAL PRIMARY KEY,
  "PARTNERID" integer NOT NULL,
  "ACCOUNTID" integer NOT NULL,
  "ISACTIVE" bool DEFAULT true,
  "CREATEDDATE" timestamptz NOT NULL DEFAULT (now()),
  "UPDATEDDATE" timestamptz
);

CREATE TABLE "USERS" (
  "USERSID" BIGSERIAL PRIMARY KEY,
  "FIRSTNAME" varchar NOT NULL,
  "MIDDLENAME" varchar NOT NULL,
  "LASTNAME" varchar NOT NULL,
  "USERNAME" varchar NOT NULL,
  "PASSWORD" varchar NOT NULL,
  "IDENTITYTYPEID" integer NOT NULL,
  "MOBILE" integer NOT NULL,
  "AGE" integer NOT NULL,
  "GENDER" varchar NOT NULL,
  "EMAIL" varchar NOT NULL,
  "ISACTIVE" bool DEFAULT false,
  "ISMOBILEACTIVE" bool DEFAULT false,
  "ISBLOCKED" bool DEFAULT false,
  "CREATEDDATE" timestamptz NOT NULL DEFAULT (now()),
  "UPDATEDDATE" timestamptz
);

CREATE TABLE "WITHDRAWALREQUESTS" (
  "WITHDRAWALREQUESTID" BIGSERIAL PRIMARY KEY,
  "REQUESTEDACCOUNTID" BIGINT NOT NULL,
  "REQUESTEDAMOUNT" BIGINT NOT NULL,
  "REQUESTEDDATE" timestamptz NOT NULL DEFAULT (now()),
  "WITHDRAWALREQUESTSTATUSID" integer NOT NULL,
  "COMMENTS" varchar,
  "WITHDRAWALREQUESTTYPEID" integer NOT NULL,
  "CURRENCYCODE" integer NOT NULL
);

CREATE TABLE "WITHDRAWALREQUESTSTATUSES" (
  "WITHDRAWLREQUESTSTAUSID" BIGSERIAL PRIMARY KEY,
  "STATUS" varchar,
  "ISACTIVE" bool DEFAULT true,
  "CREATEDDATE" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "WITHDRAWALREQUESTTYPES" (
  "WITHDRAWALREQUESTTYPEID" BIGSERIAL PRIMARY KEY,
  "NAME" varchar,
  "ISACTIVE" bool DEFAULT true,
  "CREATEDDATE" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "COMMISSIONPLANS" (
  "COMMISSIONPLANID" BIGSERIAL PRIMARY KEY,
  "COMMISSIONPLANNAME" varchar,
  "ISACTIVE" bool DEFAULT true,
  "CREATEDDATE" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "COMMISSIONRATES" (
  "COMMISSIONRATEID" BIGSERIAL PRIMARY KEY,
  "COMMISSIONPLANID" integer NOT NULL,
  "MINTRANSACTIONAMOUNT" integer NOT NULL,
  "MAXTRANSACTIONAMOUNT" integer NOT NULL,
  "COMMISSIONRATE" integer NOT NULL,
  "COMMISSIONTYPEID" integer NOT NULL,
  "ISACTIVE" bool DEFAULT true,
  "SERVICEID" Integer NOT NULL,
  "CREATEDDATE" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "COMMISSIONTYPES" (
  "COMMISSIONTYPEID" BIGSERIAL PRIMARY KEY,
  "COMMISSIONTYPENAME" varchar,
  "ISACTIVE" bool DEFAULT true,
  "CREATEDDATE" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "SERVICES" (
  "SERVICEID" BIGSERIAL PRIMARY KEY,
  "SERVICENAME" varchar,
  "SERVICECODE" integer NOT NULL,
  "IDENTITYTYPEID" integer NOT NULL,
  "ISACTIVE" bool DEFAULT true,
  "CREATEDDATE" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "IDENTITYTYPES" (
  "IDENTITYTYPEID" BIGSERIAL PRIMARY KEY,
  "IDENTITYTYPENAME" varchar,
  "ISACTIVE" bool DEFAULT true,
  "CREATEDDATE" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "CURRENCIES" (
  "CURRENCYID" BIGSERIAL PRIMARY KEY,
  "SHORTNAME" varchar,
  "CURRENCYCODE" integer NOT NULL,
  "FULLNAME" varchar,
  "SYMBOL" varchar,
  "ISACTIVE" bool DEFAULT true,
  "CREATEDDATE" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX ON "ACCOUNT" ("ACCOUNTID");

CREATE INDEX ON "ACCOUNT" ("ACCOUNTNO");

CREATE INDEX ON "PARTNERS" ("PARTNERID");

CREATE INDEX ON "PARTNERS" ("MOBILE");

CREATE INDEX ON "USERS" ("USERSID");

CREATE INDEX ON "USERS" ("MOBILE");

ALTER TABLE "ACCOUNT" ADD FOREIGN KEY ("ACCOUNTID") REFERENCES "PARTNERS" ("PARTNERID");

ALTER TABLE "ACCOUNT" ADD FOREIGN KEY ("ACCOUNTTYPEID") REFERENCES "ACCOUNTTYPES" ("ACCOUNTTYPEID");

ALTER TABLE "ACCOUNT" ADD FOREIGN KEY ("COMMISIONPLANID") REFERENCES "COMMISSIONPLANS" ("COMMISSIONPLANID");

ALTER TABLE "ACCOUNT" ADD FOREIGN KEY ("CURRENCYID") REFERENCES "CURRENCIES" ("CURRENCYID");

ALTER TABLE "TRANSFERS" ADD FOREIGN KEY ("TRANSFERTYPEID") REFERENCES "TRANSFERTYPES" ("TRANSFERTYPEID");

ALTER TABLE "TRANSFERS" ADD FOREIGN KEY ("STATUSID") REFERENCES "TRANSFERSTATUSES" ("STATUSID");

ALTER TABLE "TRANSFERS" ADD FOREIGN KEY ("SERVICEID") REFERENCES "SERVICES" ("SERVICEID");

ALTER TABLE "TRANSFERS" ADD FOREIGN KEY ("RECEIVERACCOUNTID") REFERENCES "ACCOUNT" ("ACCOUNTID");

ALTER TABLE "TRANSFERS" ADD FOREIGN KEY ("CURRENCYID") REFERENCES "CURRENCIES" ("CURRENCYID");

ALTER TABLE "PARTNERS" ADD FOREIGN KEY ("WITHDRAWALREQUESTTYPEID") REFERENCES "WITHDRAWALREQUESTTYPES" ("WITHDRAWALREQUESTTYPEID");

ALTER TABLE "PARTNERS" ADD FOREIGN KEY ("IDENTITYTYPEID") REFERENCES "IDENTITYTYPES" ("IDENTITYTYPEID");

ALTER TABLE "PARTNERS" ADD FOREIGN KEY ("COMMISSIONPLANID") REFERENCES "COMMISSIONPLANS" ("COMMISSIONPLANID");

ALTER TABLE "PARTNERACCOUNTS" ADD FOREIGN KEY ("PARTNERID") REFERENCES "PARTNERS" ("PARTNERID");

ALTER TABLE "PARTNERACCOUNTS" ADD FOREIGN KEY ("ACCOUNTID") REFERENCES "ACCOUNT" ("ACCOUNTID");

ALTER TABLE "USERS" ADD FOREIGN KEY ("IDENTITYTYPEID") REFERENCES "IDENTITYTYPES" ("IDENTITYTYPEID");

ALTER TABLE "WITHDRAWALREQUESTS" ADD FOREIGN KEY ("REQUESTEDACCOUNTID") REFERENCES "ACCOUNT" ("ACCOUNTID");

ALTER TABLE "WITHDRAWALREQUESTS" ADD FOREIGN KEY ("WITHDRAWALREQUESTSTATUSID") REFERENCES "WITHDRAWALREQUESTSTATUSES" ("WITHDRAWLREQUESTSTAUSID");

ALTER TABLE "WITHDRAWALREQUESTS" ADD FOREIGN KEY ("WITHDRAWALREQUESTTYPEID") REFERENCES "WITHDRAWALREQUESTTYPES" ("WITHDRAWALREQUESTTYPEID");

ALTER TABLE "COMMISSIONRATES" ADD FOREIGN KEY ("COMMISSIONPLANID") REFERENCES "COMMISSIONPLANS" ("COMMISSIONPLANID");

ALTER TABLE "COMMISSIONRATES" ADD FOREIGN KEY ("COMMISSIONTYPEID") REFERENCES "COMMISSIONTYPES" ("COMMISSIONTYPEID");

ALTER TABLE "COMMISSIONRATES" ADD FOREIGN KEY ("SERVICEID") REFERENCES "SERVICES" ("SERVICEID");

ALTER TABLE "SERVICES" ADD FOREIGN KEY ("IDENTITYTYPEID") REFERENCES "IDENTITYTYPES" ("IDENTITYTYPEID");
