// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/mooha76/Kofee/api"
	"github.com/mooha76/Kofee/api/service"
	"github.com/mooha76/Kofee/client"
	"github.com/mooha76/Kofee/config"
	"github.com/mooha76/Kofee/usecase"
)

// Injectors from wire.go:

func InitializeServices(cfg *config.Config) (*api.ServiceServer, error) {
	userClient, err := client.NewUserClient(cfg)
	if err != nil {
		return nil, err
	}
	authUseCase := usecase.NewAuthUsecase(userClient)
	authServiceServer := service.NewAuthServiceServer(authUseCase)
	serviceServer, err := api.NewServerGRPC(cfg, authServiceServer)
	if err != nil {
		return nil, err
	}
	return serviceServer, nil
}
